### ISSUE TITLE
InsetDivider need override `getItemOffsets()` method

### ISSUE THREAD

**Issue by laobie** [gejiaheng/Dividers-For-RecyclerView#1]
``` java
mRvApps.addItemDecoration(new InsetDivider.Builder(this).orientation(LinearLayoutManager.VERTICAL)
    .color(Color.BLACK)
    .dividerHeight(50)
    .build());
```

![image](https://cloud.githubusercontent.com/assets/7184320/18621904/ee3aaad8-7e5b-11e6-9d52-31ad61e34760.png)

**Comment by gejiaheng** [comment]
@laobie As I mentioned and cited from [Material Design Guidelines](https://material.google.com/components/dividers.html) in [README.md](https://github.com/gejiaheng/Dividers-For-RecyclerView/blob/master/README.md):

> The divider sits within the baseline of the tile.  

So I intentionally didn't implement `getItemOffsets` in `InsetDivider`。  
However you have the reason to use it like this. I mean drawing a much taller divider than a 1dp one.  
I will fix this by providing the ability to draw divider on the tile and beside it in `InsetDivider`。

**Comment by gejiaheng** [comment]
@laobie 
I've add a `mOverlay` property to `InsetDivider`, you can use `InsetDivider.Builder.overlay(boolean)` to control the drawing behavior.  
To draw a much wider divider beside the tile, you can simply pass `false` to the method.  
But I should remind you that, as you set the value to false and set inset at the same time, you may see the background of the parent of RecyclerView.

**Comment by laobie** [comment]
I got it wrong, in the case you mentioned, drawing a small  divider, it works well. Of course, when I need set a tall divider, now it works well, too.
